version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: shop-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123
      ports:
        - "3078:3306"

    backend:
      image: nginx:alpine
      container_name: shop-webserver-backend
      working_dir: /application
      volumes:
          - .:/application
          - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3040:80"

    frontend:
      image: nginx:alpine
      container_name: shop-webserver-frontend
      working_dir: /application
      volumes:
          - .:/application
          - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3050:80"

    php-fpm:
      build: docker/php-fpm
      container_name: shop-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

